In [64]:
import pandas as pd

In [65]:
dataset = pd.read_csv("Placement.csv")

In [66]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [67]:
dataset.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [7]:
#Handling the INPUT DATA -
#1) Update the missing values using CEntral Tendancy - mean,median,mode
#2) DElete the Entire Row if not impacted
#3) With respect to the problem , update the missing values
#4) Apply Semi-Supervised, Create a model , predict the values and update the missing data.

In [12]:
#dataset["salary"].fillna(0,inplace=True) # removes the NULL values in the cloumn and replace by "0"
dataset.fillna({"salary": 0}, inplace=True)

In [43]:
dataset.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [44]:
#dataset.dropna(inplace=True)  # removes the NULL values in the cloumns and replace by "0"

In [22]:
#dataset.isnull().sum()

In [24]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
7,8,M,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.0,Mkt&Fin,62.14,Placed,252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,M,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0

In [38]:
dataset["salary"].fillna(dataset["salary"].mean(), inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_16332\2165617727.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["salary"].fillna(dataset["salary"].mean(), inplace=True)

In [39]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.000000
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.000000
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.000000
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,288655.405405
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.000000
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.000000
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.000000
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.000000
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,288655.405405

In [68]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(dataset)

#Seperate the Quantitative data and give the data

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'M'

In [50]:
#Call the function Quan qual and assign to a valraible.
def quanqual(dataset):
    quan=[]
    qual=[]
    for ColumnName in dataset.columns:
           # print(ColumnName)
            if (dataset[ColumnName].dtype=='O'):
#print("it is quantitative variable / column")   #numbers may be discrete or continous
                qual.append(ColumnName)
            else:
               # print("it is qualitative variable / column")      # Categorical data - nominal, or ordinal
                quan.append(ColumnName)
    return quan,qual

In [51]:
quan,qual = quanqual(dataset)

In [69]:
dataset[quan]

     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
0        1  67.00  91.00     58.00     55.0  58.80  270000.0
1        2  79.33  78.33     77.48     86.5  66.28  200000.0
2        3  65.00  68.00     64.00     75.0  57.80  250000.0
3        4  56.00  52.00     52.00     66.0  59.43       NaN
4        5  85.80  73.60     73.30     96.8  55.50  425000.0
..     ...    ...    ...       ...      ...    ...       ...
210    211  80.60  82.00     77.60     91.0  74.49  400000.0
211    212  58.00  60.00     72.00     74.0  53.62  275000.0
212    213  67.00  67.00     73.00     59.0  69.72  295000.0
213    214  74.00  66.00     58.00     70.0  60.23  204000.0
214    215  62.00  58.00     53.00     89.0  60.22       NaN

[215 rows x 7 columns]

In [70]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(dataset[quan])

SimpleImputer()

In [55]:
imp

SimpleImputer()

In [72]:
df = imp.transform(dataset[quan])

In [73]:
df

array([[1.00000000e+00, 6.70000000e+01, 9.10000000e+01, ...,
        5.50000000e+01, 5.88000000e+01, 2.70000000e+05],
       [2.00000000e+00, 7.93300000e+01, 7.83300000e+01, ...,
        8.65000000e+01, 6.62800000e+01, 2.00000000e+05],
       [3.00000000e+00, 6.50000000e+01, 6.80000000e+01, ...,
        7.50000000e+01, 5.78000000e+01, 2.50000000e+05],
       ...,
       [2.13000000e+02, 6.70000000e+01, 6.70000000e+01, ...,
        5.90000000e+01, 6.97200000e+01, 2.95000000e+05],
       [2.14000000e+02, 7.40000000e+01, 6.60000000e+01, ...,
        7.00000000e+01, 6.02300000e+01, 2.04000000e+05],
       [2.15000000e+02, 6.20000000e+01, 5.80000000e+01, ...,
        8.90000000e+01, 6.02200000e+01, 2.88655405e+05]])

In [79]:
#convert this to a table:
df_quan_table =  pd.DataFrame(df,columns=quan)

In [80]:
df_quan_table

     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p         salary
0      1.0  67.00  91.00     58.00     55.0  58.80  270000.000000
1      2.0  79.33  78.33     77.48     86.5  66.28  200000.000000
2      3.0  65.00  68.00     64.00     75.0  57.80  250000.000000
3      4.0  56.00  52.00     52.00     66.0  59.43  288655.405405
4      5.0  85.80  73.60     73.30     96.8  55.50  425000.000000
..     ...    ...    ...       ...      ...    ...            ...
210  211.0  80.60  82.00     77.60     91.0  74.49  400000.000000
211  212.0  58.00  60.00     72.00     74.0  53.62  275000.000000
212  213.0  67.00  67.00     73.00     59.0  69.72  295000.000000
213  214.0  74.00  66.00     58.00     70.0  60.23  204000.000000
214  215.0  62.00  58.00     53.00     89.0  60.22  288655.405405

[215 rows x 7 columns]

In [86]:
df_qual_table =  dataset[qual]

In [87]:
df_qual_table

,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...
210,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [94]:
frames = (df_quan_table,df_qual_table)  # join 2 data frames
pre_processed_data = pd.concat(frames,axis=1)  #Full table qual and quan udpated. Add axis for column wise concatenation!!
pre_processed_data

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [96]:
pre_processed_data.to_csv("pre_processed_Placementdata.csv",index=False)